# Generated by Django 6.0.4 on 2026-04-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_domicilio_persona_domicilio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domicilio',
            options={'ordering': ['-id'], 'verbose_name': 'Domicilio', 'verbose_name_plural': 'Domicilios'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-id'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='no_calle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='personas.domicilio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
